### ISSUE TITLE
Problem / bug with coordinate conversion

### ISSUE THREAD

**Issue by felixgendrot** [matthewabirk/measurements#3]
Hi,
Love the package, conv_unit is quite powerful !
Unfortunately I think I ran into a strange bug with `conv_unit` when converting coordinates from "dec_deg" into "deg_dec_min".
Is it a bug or may I have a hint of what is going on ? :-)
Thanks !
```R
library(measurements)

coord_zero_dec_deg <- c(0.1, 0.01, 0.001, 0.0001, 0.00001)  
conv_unit(coord_zero_dec_deg, from = "dec_deg", to = "deg_dec_min") # problem from the fourth decimal place only for zero degree
#> [1] "0 6"      "0 0.6"    "0 0.06"   "-10000 0" "-1e+05 0"

coord_other_dec_deg <- c(1.1, 1.01, 1.001, 1.0001, 1.00001) 
conv_unit(coord_other_dec_deg, from = "dec_deg", to = "deg_dec_min") # seems to work fine
#> [1] "1 6.00000000000001"    "1 0.6"                 "1 0.0599999999999909"  "1 0.00600000000000212" "1 0.00060000000000097"
```

**Comment by matthewabirk** [comment]
Thanks for letting me know, @felixgendrot. I'll take a look at this later this week to see if I can figure out what's going on here...

**Comment by matthewabirk** [comment]
Thanks for the catch. Bug has been fixed. Checkout v1.5.1 here on Github if you need it now. I have also submitted it to CRAN and it should be available typically within a few days from them.
